[package]
name = "crust"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "crust"
path = "src/bin/main.rs"

[lib]
name = "crust_lib"
path = "src/lib/lib.rs"

[dependencies]
anyhow = "1.0.94"
chrono = { version = "0.4.39", features = ["serde"] }
config = { version = "0.14.1", features = ["yaml"] }
lettre = { version = "0.11.11", features = ["tokio1", "tokio1-native-tls"] }
log = "0.4.22"
log4rs = "1.3.0"
serde = { version = "1.0.216", features = ["derive"] }
tokio = { version = "1.42.0", features = ["full"] }
