tasks:
  - command: "echo 'hello world'"
    schedule:
      hour: "*"
      minute: "*"
      second: "*"

  - command: "lse /tmp"
    schedule:
      hour: "14"
      minute: "*"
      second: "*"

notifiers:
  email:
    host: "smtp.gmail.com"
    port: 465
    username: "xxx@gmail.com"
    password: "xxx"
    from: "xxx@gmail.com"
    to: "xxx@gmail.com"
