tasks:
  - command: "echo 'hello world'"
    schedule:
      hour: 00
      minute: 00
      second: 00

  - command: "lse /tmp"
    schedule:
      hour: 00
      minute: 00
      second: 00

notifiers:
  email:
    host: "smtp.gmail.com"
    port: 465
    username: "xxx@gmail.com"
    password: "xxx"
    from: "xxx@gmail.com"
    to: "xxx@gmail.com"
